### ISSUE TITLE
[ENH] Cleaner env var use for acr script

### ISSUE THREAD

**Issue by lmeyerov** [graphistry/graphistry-helm#11]
**Is your feature request related to a problem? Please describe.**

Directly using the acr script doesn't work because it hardcodes using a bogus env file

This is frustrating b/c prevents direct use as a git checkout ( cc @ceteri )

**Describe the solution you'd like**

- [ ] Line https://github.com/graphistry/graphistry-helm/blob/eaefb2e07004371deba23ec054bd68346a7703d1/acr-bootstrap/import-image-into-acr-from-dockerhub.sh#L6 should be removed as it is the responsibility of the script caller to setup the env

- [ ] ... and get that line as a sample usage added to a README.md

- [ ] ... and for the script, add a preamble documenting the expected env vars and warn+throw an error  if any required are empty/missing

**Comment by webcoderz** [comment]
resolved via this commit: https://github.com/graphistry/graphistry-helm/commit/3d7784fa7fbe6b8999ef437a6f005bb2252d8d79
