### ISSUE TITLE
cookie config

### ISSUE THREAD

**Issue by lmeyerov** [graphistry/graphistry-helm#38]
k8s migrations may not be transferring secrets/cookies property? the "white screen" bug

Requires internal triage/planning first (leo, thomas, percy, cody)

**Comment by lmeyerov** [comment]
Marking p3 as both real but temporarily assuaged

**Comment by webcoderz** [comment]
The session cookies are being set as https://github.com/graphistry/graphistry-helm/blob/9a987b48323daf62a1c4239590ef6727dcd848da/charts/graphistry-helm/templates/ingress/caddy-ingress.yml#L11 here which should  pass the session cookie to to be ingressed out 

Maybe there’s some other settings that have to be configured 
https://kubernetes.github.io/ingress-nginx/examples/affinity/cookie/

**Comment by lmeyerov** [comment]
I suspect the issue is that they're putting up a new server that has new secret keys, so all the signing is busted when using an old cookie on a new nexus

I'm not sure which cookies might be doing it --

Dockerfile: https://github.com/graphistry/graphistry/blob/master/compose/dockerfiles/graphistry/nexus/nexus.Dockerfile

Django base settings: https://github.com/graphistry/graphistry/blob/master/apps/core/nexus/config/settings/base.py


Some secret nonces of interest:

* SECRET_KEY=DJANGO_SECRET_KEY
* JWT_SECRET_KEY (= SECRET_KEY)

So maybe they just need to set DJANGO_SECRET_KEY? Any way to do that?

@vaimdev  any other ideas?

**Comment by webcoderz** [comment]
Yea I pointed out the django secret key value in our meeting the other day.. actually I should probably move these to secrets and not make them optional , what do you think? At time they didn't seem necessarily important for secrets but if they're using in prod and serving customers it's prob imp to use proper security practices

**Comment by lmeyerov** [comment]
Agreed, and having them reuse across deploys may help with the bug

@DataBoyTX maybe worth trying to reproduce the issue first before claiming a fix of the issue?

**Comment by webcoderz** [comment]
Yea that would just be sharing the secret across namespaces if I had to guess (if they're doing diff deployments segmented by namespaces) they should just be able to do a non namespace scoped secret to handle all of them.

**Comment by lmeyerov** [comment]
i think safe to close after debug sessions w/ bbai, we'll see if comes again
